# Generated by Django 4.2.2 on 2023-07-26 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=50)),
                ('trainer_phno', models.BigIntegerField()),
                ('trainer_email', models.CharField(max_length=50)),
                ('trainer_salary', models.IntegerField()),
                ('teaching_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.course')),
                ('trainer_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.city')),
            ],
        ),
    ]
